version: "3.3"
services:

  frontend:
    image: juanmardefago/arq1-frontend
    ports:
      - "80:5000"
    depends_on:
      - backend
  backend:
    image: juanmardefago/arq1-backend
    network_mode: host
    volumes:
      - ./data/logs:/home/feathers/logs
      - ./data/public/uploads:/home/feathers/public/uploads
    environment:
      - MONGODB_URL=mongodb://localhost:27018/backend
      - PORT=3030
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0.10-xenial
    ports:
      - "27018:27017"
    volumes:
      - ./data/db:/data/db
