version: "3.3"
services:

  frontend:
    image: juanmardefago/arq1-frontend
    ports:
      - "80:5000"
    depends_on:
      - backend
  backend:
    image: juanmardefago/arq1-backend
    ports:
      - "3030:3030"
    environment:
      - MONGODB_URL=http://mongo:27017/backend
      - PORT=3030
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0.10-xenial
